export default {
  COMING_SOON_ROUTE_NAME: "COMING_SOON",

  PRODUCT_DETAIL: "PRODUCT_DETAIL",
  MENU: "MENU",
  VIEW_ALL: "VIEW_ALL",
  UserLocation: 'UserLocation',
  MYORDERS: 'MYORDERS',
  MANAGE_ADDRESS: 'MANAGE_ADDRESS',
  MYFAVOURITES: 'MYFAVOURITES',
  TERMS_AND_CONDITIONS: 'TERMS_AND_CONDITIONS',
  HELP: 'HELP',
  CONTACT_US: 'CONTACT_US',
  ORDER_DETAIL: 'ORDER_DETAIL',
};
